import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import { QuizProvider } from "./contexts/QuizContext";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ScannTech Quiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={sora.className}>
        <QuizProvider>{children}</QuizProvider>
      </body>
    </html>
  );
}
